# Generated by Django 3.2.11 on 2022-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decaptcha', '0003_captchalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchausage',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
    ]
