# Generated by Django 3.2.11 on 2022-01-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decaptcha', '0004_captchausage_fail_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchalog',
            name='train1',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='captchalog',
            name='train2',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
